name: Update Submodules

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          persist-credentials: true
          fetch-depth: 0
          token: ${{ secrets.PAT }} 
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

      - name: Update submodule to specific branch
        run: |
          cd luci-theme-kucat
          git fetch origin
          git checkout js
          git pull origin js
          cd ..

      - name: Debug submodules
        run: |
          git submodule status
          git status

      - name: Commit submodule updates (if any)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Update submodules"
            git push origin main
          fi
